// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type PingRpcReq struct {
	Message string `form:"message,optional,default=hello"`
}

type PingRpcResp struct {
	Pong string `json:"pong"`
}

type UserInfoReq struct {
	Id int64 `path:"id"`
}

type UserInfoResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
